def build_explanation(
    diagnosis: str,
    confidence: float,
    probabilities: list[dict[str, float | str]],
) -> str:
    pct = confidence * 100
    label = diagnosis.replace("_", " ").title()

    if diagnosis.upper() == "PNEUMONIA":
        finding = (
            f"The model classified this chest X-ray as **{label}** with {pct:.1f}% confidence. "
            "Radiographic patterns such as focal or diffuse opacities in the lung fields "
            "were weighted heavily in this prediction. Grad-CAM highlights regions that "
            "most influenced the decision—typically areas of increased density."
        )
        recommendation = (
            "This result is for decision support only. Correlate with clinical history, "
            "vital signs, and laboratory findings. Consider confirmatory imaging or "
            "microbiological workup per institutional protocol."
        )
    else:
        finding = (
            f"The model classified this chest X-ray as **{label}** with {pct:.1f}% confidence. "
            "No dominant pneumonia-associated opacity pattern was detected above the "
            "decision threshold. Grad-CAM shows relatively lower activation in typical "
            "consolidation regions."
        )
        recommendation = (
            "Continue standard clinical assessment. If symptoms persist despite a "
            "negative screening result, pursue additional diagnostic evaluation."
        )

    alt = [
        p for p in probabilities
        if str(p["label"]).upper() != diagnosis.upper()
    ]
    alt_text = ""
    if alt:
        top_alt = max(alt, key=lambda x: float(x["confidence"]))
        alt_pct = float(top_alt["confidence"]) * 100
        alt_text = (
            f" Alternative consideration: {str(top_alt['label']).replace('_', ' ').title()} "
            f"({alt_pct:.1f}% estimated probability)."
        )

    return (
        f"**AI Interpretation Summary**\n\n{finding}{alt_text}\n\n"
        f"**Clinical Note**\n\n{recommendation}\n\n"
        "*Generated by MedVision AI — not a substitute for professional medical judgment.*"
    )
