from app.ml.labels import HIGH_RISK_DX, LESION_DISPLAY_NAMES


def build_explanation(
    diagnosis: str,
    confidence: float,
    probabilities: list[dict[str, float | str]],
) -> str:
    pct = confidence * 100
    dx = diagnosis.lower()
    label = LESION_DISPLAY_NAMES.get(dx, diagnosis.replace("_", " ").title())

    if dx in HIGH_RISK_DX:
        finding = (
            f"The model classified this dermoscopic image as **{label}** ({dx}) "
            f"with {pct:.1f}% confidence. Patterns in pigment network, asymmetry, "
            "or vascular structures in the lesion region contributed to this "
            "prediction. Grad-CAM highlights areas that most influenced the decision."
        )
        recommendation = (
            "This result is for decision support only. Correlate with dermatoscopic "
            "examination, patient history, and dermoscopy. Consider biopsy or specialist "
            "referral per institutional dermatology protocol for suspicious lesions."
        )
    else:
        finding = (
            f"The model classified this dermoscopic image as **{label}** ({dx}) "
            f"with {pct:.1f}% confidence. Grad-CAM shows which lesion regions "
            "drove the classification relative to other HAM10000 categories."
        )
        recommendation = (
            "Continue clinical follow-up as indicated. If morphology changes or "
            "symptoms evolve, repeat imaging and consider specialist review."
        )

    alt = [p for p in probabilities if str(p["label"]).lower() != dx]
    alt_text = ""
    if alt:
        top_alt = max(alt, key=lambda x: float(x["confidence"]))
        alt_dx = str(top_alt["label"]).lower()
        alt_label = LESION_DISPLAY_NAMES.get(alt_dx, alt_dx)
        alt_pct = float(top_alt["confidence"]) * 100
        alt_text = (
            f" Alternative consideration: {alt_label} ({alt_dx}) "
            f"— {alt_pct:.1f}% estimated probability."
        )

    return (
        f"**AI Interpretation Summary**\n\n{finding}{alt_text}\n\n"
        f"**Clinical Note**\n\n{recommendation}\n\n"
        "*Generated by MedVision AI — not a substitute for professional medical judgment.*"
    )
